set -g mouse on

# Copy mouse selections directly to system clipboard upon releasing the mouse button
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"

# Copy text to system clipboard when pressing Enter/y in Copy Mode
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
